### ISSUE TITLE
Hi, It's show black screen.

### ISSUE THREAD

**Issue by ninenox-dev** [omatt/RTMP-stream-demo#1]
How to fix it?
I try to change url already, It's show black screen same.

**Comment by omatt** [comment]
Currently tracking this issue on https://github.com/omatt/RTMP-stream-demo/issues/2. Haven't touch this project for a while. I'm still debugging this issue.

**Comment by omatt** [comment]
Vitamio has been discontinued. I'll be closing this ticket.
